dubbo:
  application:
    name: dubbo-springboot-demo-consumer
    qos-enable: true
    qos-port: 33333
    qosAcceptForeignIp: true
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:43.142.18.133}:2181
server:
  port: 8081